### ISSUE TITLE
reduce swipe sensitivity

### ISSUE THREAD

**Issue by withoutfield** [GianlucaGuarini/Tocca.js#13]
Is it possible to reduce sensitivity of the left / right swipe gestiture? When I fast scroll the page I always load a new sie because my vertical swipe Action is not straight enough. So now the swipe is too sensitive for me. 
Is there a way to adjust a Minimum vertical Distance before Action Starts?
Ps: I am using tocca.js with the wordpress Plugin.
Cheers, pEtEr

**Comment by GianlucaGuarini** [comment]
Just change the swipe threshold property https://github.com/GianlucaGuarini/Tocca.js#configuration

**Comment by withoutfield** [comment]
Great, thank you!
