### ISSUE TITLE
Double-tap doesn't seem to work on KitKat Chrome or Safari iOS 8

### ISSUE THREAD

**Issue by gtnewton** [GianlucaGuarini/Tocca.js#14]
Thanks for this lib. It's fabulous and I'm using it successfully in a couple projects. However, I recently wanted to add 'double-tap to go fullscreen' functinoality, but I've been unable to make dbltap work. I don't think it's just me: your demo does not seem to register double-taps either.
Thanks!

**Comment by GianlucaGuarini** [comment]
Are you sure the bug it's not in your app? Because from here everything works fine on android

**Comment by GianlucaGuarini** [comment]
Even if it's a bit small you should be able to see the event type="dbltap"
![screen shot 2015-02-28 at 00 41 29](https://cloud.githubusercontent.com/assets/879612/6423184/9eb81002-bee2-11e4-8ca1-efdc3088bc7b.png)

**Comment by gtnewton** [comment]
Hm. Maybe I'm doing something wrong, but I don't think so. When I go [here](http://gianlucaguarini.github.io/Tocca.js/demo-fun.html) on my phone (Nexus 5, KitKat, Chrome, up-to-date) and double-tap I get 'Event Name tap'. I get the same response on an iPad (iOS 8) and a Nexus 7 (KitKat, up-to-date, etc.) and Chrome on my desktop machine (Chromium 40.0.2214.111).
I noticed your screenshot, but I don't get that 'dbltap'. It doesn't look like you're using KitKat, though. Perhaps that's the problem(?)

**Comment by GianlucaGuarini** [comment]
What if you increase this value `DBL_TAP_THRESHOLD` ?

**Comment by gtnewton** [comment]
I just tried it on Firefox (on my phone), and it *does* work. I think this might be a KitKat/Chrome thing...
Oh, I did try increasing that threshold. No go.

**Comment by GianlucaGuarini** [comment]
I get the dbltap on the ipad as well 
![screen shot 2015-02-28 at 00 48 54](https://cloud.githubusercontent.com/assets/879612/6423270/9e878b02-bee3-11e4-9012-c7d2d67e29a6.png)

**Comment by gtnewton** [comment]
The iPad I'm using is an iPad 3 (physical), running iOS 8.1.3.

**Comment by GianlucaGuarini** [comment]
Ok so It needs to be checked a bit better thanks for your bug report. Do you have the same problem on the old Toccajs (0.1.0) releases?

**Comment by gtnewton** [comment]
Good question. I'll try it and let you know.

**Comment by gtnewton** [comment]
Aha! It works on the iPad *and* my phone.

**Comment by GianlucaGuarini** [comment]
do you mean the old release?

**Comment by gtnewton** [comment]
Sorry. Yes. I checked out 0.1.0 and it works on both devices.

**Comment by GianlucaGuarini** [comment]
Also on android 5 it works
![screen shot 2015-02-28 at 01 08 48](https://cloud.githubusercontent.com/assets/879612/6423446/673aa866-bee6-11e4-8a13-929a16295ec0.png)

I have tested old ipads android opera... and it works everywhere obviously on the emulators. I will check on monday in the office to see if the issue appears on the real devices

**Comment by gtnewton** [comment]
OK. Thanks for the quick responses. I'm happy to test on the physical devices I have access to.

**Comment by gtnewton** [comment]
I just realized that I made a stupid mistake. I'm not using Android Kitkat anymore. I'm on Android Lollipop (5.0.1). And I see that you aren't saying that you support 5.0 yet. Sorry for the confusion. I can wait for Lollipop support if it isn't a current priority for you.

**Comment by GianlucaGuarini** [comment]
Could you please try the Tocca.js version available on  [this branch](https://github.com/GianlucaGuarini/Tocca.js/tree/bug/dbltap) ?

**Comment by gtnewton** [comment]
That looks good! It registers dbltap on my Nexus 5, Nexus 7 and my iPad.

**Comment by GianlucaGuarini** [comment]
Awesome thanks for your help

**Comment by gtnewton** [comment]
No, thank you! That was fabulous. I really appreciate your effort. Cheers!
