### ISSUE TITLE
Not working on my HTC E8

### ISSUE THREAD

**Issue by Voyga** [GianlucaGuarini/Tocca.js#18]
Works well on ios and some other android devices, but not working on my htc e8.

**Comment by GianlucaGuarini** [comment]
Could provide more details please?

**Comment by Voyga** [comment]
```javascript
document.body.addEventListener("swipeleft", App.moveLeft);
document.body.addEventListener("swiperight", App.moveRight);
```
This is my code. Nothing happened when I swipe. This only occurs on my htc e8.

**Comment by GianlucaGuarini** [comment]
I think your device does not support the touch events. You should include a polyfill https://github.com/Deltakosh/handjs
