### ISSUE TITLE
Click events do not fire in Chrome Win 8.1 touch laptops

### ISSUE THREAD

**Issue by anushr** [GianlucaGuarini/Tocca.js#20]
OS: Win 8.1 (touch enabled)
Browser: Chrome 42.0

The "tap" events do not fire when the mouse is used to perform an interaction. A mouse click does not fire a "tap" event. Touch interactions however do work correctly and fire a "tap" event.

This issue has been reproduced on several touch enabled Win 8.1 laptops. This seems to affect only Chrome. Both Firefox and IE work fine i.e. they do fire "tap" events on click.

On investigation, it appears that `isTouch` is `true` on Chrome and when this is the case, mouse events are not registered.

https://github.com/GianlucaGuarini/Tocca.js/blob/master/Tocca.js#L158

I'm wondering why the lib is listening only to touch events when a touch device is detected? Shouldn't it listen to both touch and click since it could be a touch and click device? 

My suggestion would be to not listen to click events only if the user has explicitly asked for that via `JUST_ON_TOUCH_DEVICES`. In all other cases, it should listen to both.

**Comment by GianlucaGuarini** [comment]
I will find a solution to handle the events also on the hybrid devices..btw this seems to me more a chrome bug than a Tocca.js one

**Comment by anushr** [comment]
Actually, I think Chrome is the only browser correctly reporting `isTouch=true`. FF and IE report `isTouch=false`, which I guess is incorrect considering that a hybrid device may also be considered a touch device.

**Comment by GianlucaGuarini** [comment]
After several tests I should admit that this issue is harder than I thought on the hybrid devices and cannot be solved. In fact if chrome returns `isTouch=true` on an hybrid device why then it does not trigger the touch events but it uses only to the mouse events? This makes no sense! If I try to bind both `mousedown touchstart` (without any isTouch flag) they will get triggered in sequence on all the touch devices generating then a `dbltap` event. I think maybe you should use a custom script in your case, because I can not imagine any possible solution to this issue.

**Comment by anushr** [comment]
@GianlucaGuarini I tried out 0.2.0-beta.2. Here are my test results with the `tap` event.

**On a standard non-touch laptop, Win10:**
* does not respond to mouse clicks in Firefox (v41.0.2)
* inconsistent results with Chrome (46.0.2490.71 m) -- mostly works but does not work intermittently; investigating why
* works fine on IE and Edge

**On hybrid laptop**
* TBD

**On touch devices (android, ios)**
* works fine for touch events across many devices

**Comment by GianlucaGuarini** [comment]
@anushr I can not test script only on the windows Hybrid devices, so if you have one it would be nice to see how it behaves

**Comment by GianlucaGuarini** [comment]
this patch https://github.com/GianlucaGuarini/Tocca.js/commit/b41652fb8c0803d852a65a49b98e18f038ae0857 should have fixed the issue

**Comment by GianlucaGuarini** [comment]
@anushr I will close this issue, feel free to reopen it again if the problem was not fixed yet in your case
