### ISSUE TITLE
Uncaught TypeError: customEvent.initEvent is not a function in v0.1.5

### ISSUE THREAD

**Issue by sqal** [GianlucaGuarini/Tocca.js#23]
Hi. Just noticed that Tocca.js in the latest version 0.1.5 throws the following error in the browser console:

```Uncaught TypeError: customEvent.initEvent is not a function Tocca.js:83```  (http://prntscr.com/7ooudi)

I checked prevous versions and 0.1.4 does not have this bug.

**Comment by sqal** [comment]
Oh and seems like this error occurs only when we use jQuery to attach an event (tested with jQuery 1.11.3 and 2.1.4)

**Comment by allcode** [comment]
Fixed in pull request #24

**Comment by GianlucaGuarini** [comment]
thanks for raising up this issue ;)
