### ISSUE TITLE
Checking of touch devices is wrong

### ISSUE THREAD

**Issue by manum176** [GianlucaGuarini/Tocca.js#28]
Checking of touch devices is wrong I think. There is problem with some browsers including chrome. So I changed the 'isTouch' assignment to /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent). Now it is fine I think. 

Can you please check it? I think my solution is not robust.

**Comment by GianlucaGuarini** [comment]
Can't we combine both? I think userAgent sniffing is a [bad practice](https://developer.mozilla.org/en-US/docs/Browser_detection_using_the_user_agent). Which kind of problems did you find?

**Comment by manum176** [comment]
Sometimes, 'isTouch' will return true for chrome. This causes the mouse events not to register in chrome and 'tap' event will not work at all.

**Comment by GianlucaGuarini** [comment]
on which device so I could test it

**Comment by manum176** [comment]
Apologies. I am not able to find the issue now. I got the issue in windows 8.1. I will certainly update you if I get it again. It works with all browsers now. 

Anyway, thanks for a nice library.

**Comment by manum176** [comment]
I got the problem with IE Mobile 11 in Nokia Lumia 520. After a tap event, every tap event is becoming a double tap event.

**Comment by manum176** [comment]
The problem is at the 'msEventType' method where it registers mspointer events and touchstart events  together in IE Mobile which causes a tap to work as double tap. So I checked if the device is IE Mobile and resolved it temporarily for my application.

Thanks
