### ISSUE TITLE
Understanding tocca.js events - help required

### ISSUE THREAD

**Issue by Vandenberg** [GianlucaGuarini/Tocca.js#30]
So this is how I've used tocca for touch events.
	bar1 = $("#myDIv").find('.dragMarker');
	bar1.on('touchstart',setCurrent);
	bar1.on('mousedown',setCurrent);		

	function setCurrent(e,data) {
		current = 1;
		reset();
	}

I want to pass an integer like this:

    $.mousedown(setCurrent(i))

	function setCurrent(j) {
		return function(event) { 
			current = j;
			reset();
		}
	}

How to combine it so that I can link both actions to the same function? ie. function setCurrent(e,data,i)

Thanks :)

**Comment by GianlucaGuarini** [comment]
I am not sure I understand what you are trying to do, but in your code there is no one events provided by Tocca.js. Can you make a simple jsfiddle please?

**Comment by Vandenberg** [comment]
Yes I have just set one up: https://jsfiddle.net/Siemvandenberg/3gnz8209/

Altough some tocca beheviour might be commented out

**Comment by GianlucaGuarini** [comment]
@Vandenberg I am not sure what you are trying to do but I guess [this example](https://jsfiddle.net/5pxvLdb6/1/) may help you

**Comment by Tomorrows** [comment]
When I packed with r.js's   require.js,
JQuery writes tap effectively
Dian=$var ('#dian');
Dian.on ('tap', function (E, data) {//it's worker
Alert (Dian tap'jquery 1111');
});
But with the native JS, there is no effect, if I pack an error, jQuery bound tap certainly invalid
Dian2=document.getElementById var ("dian2");    //it's  don't work
Dian2.addEventListener ('tap', function (E) {
Alert (dian2 tap'js);
});

**Comment by Tomorrows** [comment]
When I packed with r.js's require.js,JQuery writes tap effectively
 var  dian=$('#dian');
  dian.on('tap',function(e,data){      //it's  word
	   alert('jquery dian  tap dian');
	   });

But with the native JS, there is no effect, if I pack an error, jQuery bound tap certainly invalid

 var dian2=document.getElementById("dian2");  //it's  don't work
	dian2.addEventListener('tap',function(e){
	    alert('js  dian2 tap  dian2');
	
	});

**Comment by GianlucaGuarini** [comment]
I will close this issue I provided a valid solution to pass value to the `tap` callback and for me it's ok so. Thank you for your questions
