### ISSUE TITLE
Question: Any angularjs examples for swipe events?

### ISSUE THREAD

**Issue by grahamlittle** [GianlucaGuarini/Tocca.js#31]
i would like to override the default swipe events to stop select elements etc from being opened when a user is swiping on a mobile.

I have added the Tocca.js to my page and in the page controller I am attempting to bind the <form> and addEventListeners for the swipe events so that i can just ignore the default behaviour something like this:

1) get form element

      var elm = document.getElementsByTagName("form");
 
2) attach listeners   

      elm.addEventListener('swipeleft',helpSwipe(e));
      elm.addEventListener('swiperight',helpSwipe(e);
      elm.addEventListener('swipeup',helpSwipe(e));
      elm.addEventListener('swipedown',helpSwipe(e));

3) manipulate event behaviour

      function helpSwipe(e) {
      var touches = evt.changedTouches || (evt.originalEvent && evt.originalEvent.changedTouches);
      if (evt.type === 'touchstart') {
        initialTouchStartY = touches ? touches[0].clientY : 0;
        return true; // don't block event default
      } else {
        evt.stopPropagation();
        evt.preventDefault();

        // prevent scroll from triggering event
        if (evt.type === 'touchend') {
          var currentLocation = touches ? touches[0].clientY : 0;
          if (Math.abs(currentLocation - initialTouchStartY) > 20) return false;
        }
      }
      }

the problem i have at the moment is that in stage two it is not allowing me to attach the listener to the elm - *elm.addEventListener is not a function*. I am sure i am missing something very simple thats why i am asking for angularjs example to see.

many thanks

**Comment by GianlucaGuarini** [comment]
Hi,
`getElementByTagName` returns an array so you can not use
`addEventListener`. Probably the only thing you need to change is `var elm
= document.getElementByTagName("form")[0]`
Good luck

2015-11-18 14:40 GMT+01:00 Graham Little <notifications@github.com>:

> i would like to override the default swipe events to stop select elements
> etc from being opened when a user is swiping on a mobile.
>
> I have added the Tocca.js to my page and in the page controller I am
> attempting to bind the
> and addEventListeners for the swipe events so that i can just ignore the
> default behaviour something like this:
>
> 1) get form element
>
>   var elm = document.getElementsByTagName("form");
>
> 2) attach listeners
>
>   elm.addEventListener('swipeleft',helpSwipe(e));
>   elm.addEventListener('swiperight',helpSwipe(e);
>   elm.addEventListener('swipeup',helpSwipe(e));
>   elm.addEventListener('swipedown',helpSwipe(e));
>
> 3) manipulate event behaviour
>
>   function helpSwipe(e) {
>   var touches = evt.changedTouches || (evt.originalEvent && evt.originalEvent.changedTouches);
>   if (evt.type === 'touchstart') {
>     initialTouchStartY = touches ? touches[0].clientY : 0;
>     return true; // don't block event default
>   } else {
>     evt.stopPropagation();
>     evt.preventDefault();
>
>     // prevent scroll from triggering event
>     if (evt.type === 'touchend') {
>       var currentLocation = touches ? touches[0].clientY : 0;
>       if (Math.abs(currentLocation - initialTouchStartY) > 20) return false;
>     }
>   }
>   }
>
> the problem i have at the moment is that in stage two it is not allowing
> me to attach the listener to the elm - *elm.addEventListener is not a
> function*. I am sure i am missing something very simple thats why i am
> asking for angularjs example to see.
>
> many thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GianlucaGuarini/Tocca.js/issues/31>.
>



-- 
*Gianluca Guarini*


*Frontend Developer || Web Designerwww.gianlucaguarini.com
<http://www.gianlucaguarini.com>@gianlucaguarini
<https://twitter.com/gianlucaguarini>*

**Comment by grahamlittle** [comment]
Yes that was it!!! thanks a lot @GianlucaGuarini
