### ISSUE TITLE
Tap event triggered when doubletapped?

### ISSUE THREAD

**Issue by vasanthv** [GianlucaGuarini/Tocca.js#32]
Hi,

First of all I have to say that it is an awesome library which I use in all my recent projects.

But one strange thing is every time I doubletap a tap event is also fired. Is there a way to stop this behaviour?

Thanks
Vasanth

**Comment by GianlucaGuarini** [comment]
Hi @vasanthv thanks but this behavior is not strange it's how the browsers work. This issue is a duplicate https://github.com/GianlucaGuarini/Tocca.js/issues/26 and I am closing it. Thank you anyway
