### ISSUE TITLE
'tap' event is not triggered in a proper way on Android devices (Samsung, HTC, Nexus 5)

### ISSUE THREAD

**Issue by like-me1** [GianlucaGuarini/Tocca.js#33]
'tap' event triggers normal click on Android devices instead of short 'tap'. 'dbtap' also doesn't work properly. But it both of these events work fine on iPhone devices.

**Comment by GianlucaGuarini** [comment]
Could you explain better the issue please? Have you checked your devices on the [demo](http://gianlucaguarini.github.io/Tocca.js/demo-fun.html)? On my android all the events get fired properly
