### ISSUE TITLE
how to integrate with riot.js 

### ISSUE THREAD

**Issue by leekangtaqi** [GianlucaGuarini/Tocca.js#34]
I import Tocca and riot(2.0.12), but it doesn't work.

    <div ontap="{test}"></div>
    this.test = function(){
        ...
    }

Is it conflict with the nature event of riot ?

**Comment by GianlucaGuarini** [comment]
[no](http://plnkr.co/edit/3njCUhc0edXTrGcRXZ5y?p=preview)

**Comment by leekangtaqi** [comment]
1. it does not always respond.
2. The tap event will not bubble
3. it conflict with click

**Comment by GianlucaGuarini** [comment]
> it does not always respond.

Have you tried to change the [configuration](https://github.com/GianlucaGuarini/Tocca.js#configuration)?

> The tap event will not bubble

hmm this is a bug I must fix it!

> it conflict with click

You should not use both, either you use the tap or the click events. The tap events get dispatched also on the desktop devices

**Comment by GianlucaGuarini** [comment]
The events bubbling does now work only for the inline listeners https://jsfiddle.net/gianlucaguarini/uwe4upn6/

**Comment by GianlucaGuarini** [comment]
fixed in Tocca.js 1.0.0
