### ISSUE TITLE
ontap event handler not called on parent element

### ISSUE THREAD

**Issue by epidemian** [GianlucaGuarini/Tocca.js#35]
If a "tap" event listener is set using `ontap` on a parent element, taps to the children elements don't seem to trigger that listener. Try tapping/clicking on the "inner" and "outter" elements on [this jsFiddle](https://jsfiddle.net/9Lo82hhp/) as an example.

However, when using `addEventListener`, the event handler on the parent is called even when the tap event originates from a child. [Modified jsFiddle](https://jsfiddle.net/70v4azy2/).

Shouldn't these two methods of setting an event listener be equivalent in this case? (for reference, using `onclick` on the parent element does work for clicks on its children)

Thanks for this awsome library! :smiley_cat:

**Comment by GianlucaGuarini** [comment]
fixed in Tocca.js 1.0.0

**Comment by epidemian** [comment]
Awesome! Thanks @GianlucaGuarini, and congrats on the 1.0.0 release! :tada:
