### ISSUE TITLE
Swiping event

### ISSUE THREAD

**Issue by anaibol** [GianlucaGuarini/Tocca.js#36]
Hi! I am trying to build something like this: http://damusnet.github.io/react-swipe-views/
I am using Tocca.js for swipeLeft and swipeRight events.
I think that having new events like 'swiping' or 'swipingLeft' would give more power to this library since in for 'native like' ux on mobile we need it.

**Comment by GianlucaGuarini** [comment]
Why? Can't you use the `touchmove` events?

**Comment by anaibol** [comment]
Yes but it's like a dragging event, swipe direction + move. It's doable manually, but it would be very cool to have it. Swiping direction is a common pattern on mobile interaction as we see on native ios and android apps.

**Comment by ajaywebaroo** [comment]
works only on tag elements not classes in jquery

**Comment by anaibol** [comment]
So :(
