### ISSUE TITLE
Swipe in a diagonal direction should not emit any events

### ISSUE THREAD

**Issue by prateekbh** [GianlucaGuarini/Tocca.js#39]
Hi,
lets say i swiped in top left direction, in that case a swipeLeft or a swipeUp event should not be fired, cuz it creates a really bad UX.
imagine the page scrolled up and due to swipeLeft, the tabs also changed.

**Comment by Marchrius** [comment]
IMHO, the best choice is to set a minimum of tolerance for the swipe direction and priority.

**Comment by prateekbh** [comment]
@Marchrius @GianlucaGuarini as I see in native apps if i start swiping left/right and then move towards up/down it doesnt scroll up/down.. need to implement something like that

**Comment by prateekbh** [comment]
for now fixing it like this 

on touchMove event listener

```
var scrollDirectionIntent = Math.abs(initPoint.clientX - e.touches[0].clientX)/Math.abs(initPoint.clientY - e.touches[0].clientY);
if(scrollDirectionIntent > 0.8){
	e.preventDefault();
}
```

**Comment by karneaud** [comment]
i'm looking at this as well...was this implemented?

**Comment by prateekbh** [comment]
It can be solved as I commented up ^

**Comment by karneaud** [comment]
ok....so you're saying it has not being implemented in latest version....ok

**Comment by GianlucaGuarini** [comment]
@prateekbh could you please create a PR? I will be happy to merge it and bump a major release

**Comment by scottbuscemi** [comment]
> initPoint

@prateekbh Three years later, but... :) If you remember this-- 

I'm seeing initPoint as undefined. How did you define this?

**Comment by prateekbh** [comment]
woah thats a walk down the memory lane.
At this point my best guess is that initPoint was the point where touchDown/mouseDown started.

**Comment by GianlucaGuarini** [comment]
I am closing this issue because this feature will not be supported and the script provides already via `event.data.distance` all the values needed for a diagonal swipe detection.
