### ISSUE TITLE
use tap and dbl tap for the same elem

### ISSUE THREAD

**Issue by xutech** [GianlucaGuarini/Tocca.js#40]
Hello, 

`$('img').on('dbltap',function(e,data){
	alert('dbltap');
 });
$('img').on('tap',function(e,data){
	alert('tap');
});`

How i can prioritize the event dbltap ? If dbltap, don't launch tap event.. Thanks.

**Comment by GianlucaGuarini** [comment]
You could use a timer in this way http://plnkr.co/edit/WTCVhIUvQhAOVykxKZad?p=preview 
Unfortunately you can not have a dblptap without a tap event first
