### ISSUE TITLE
conflicts with other swipe elements

### ISSUE THREAD

**Issue by regelga** [GianlucaGuarini/Tocca.js#41]
I use Tocca to swipe between pages and it works great, except where a nested element is also responding to swipes.  Typically this appears with Google maps and image sliders.

Is there a way to exclude these nested elements from Tocca's attention?  If not, please consider for enhancement.

**Comment by GianlucaGuarini** [comment]
Yes there is and the solution is the same you would use with any other js event. Javascript provides the `event.stopPropagation()` method to solve this kind of issue http://plnkr.co/edit/OmuAtDEUnQxR2NuORDUj?p=preview
