### ISSUE TITLE
Single-click/tap interpruted as double on Windows/Andriod Chrome

### ISSUE THREAD

**Issue by stevland** [GianlucaGuarini/Tocca.js#45]
I appreciate your code. 

Unfortunately, it did not work as intended on my blog. 

_Any_ single click/tap would take me back to the home page. Even clicking on a link meant to point elsewhere.

I also found that swiping was far too sensitive... one could not even highlight some text on the page without unexpectedly being thrust onto another page.

I disabled every other plugin and switched themes to no avail.

The single-click/tap issue only presented itself on Win/Android Chrome in my tests. Although I found that highlighting text would trigger a swipe action on FF/IE/Edge as well as Chrome.

It was driving me crazy, so I had to disable it. I read through the issues and I'm surprised that I am the only person reporting this. 

An aside: IMO there is no useful purpose for Tocca to work on desktop browsers. I would recommend detecting mobile vs. desktop browsers and at least having the option to enable/disable the script on desktop browsers.

**Comment by stevland** [comment]
P.S. WordPress 4.7
Chrome 55.0.2883.87 m (64-bit)
FF 50.1.0

**Comment by GianlucaGuarini** [comment]
Tocca.js has nothing to do with wordpress, I am not responsible of third party extensions using my library. Please contact the wordpress plugin author
