### ISSUE TITLE
Reverse swipe direction

### ISSUE THREAD

**Issue by dillscallion** [GianlucaGuarini/Tocca.js#46]
I installed a wordpress plugin which utilizes the Tocca.js. It is called Gesture (https://premium.wpmudev.org/blog/easily-add-touch-gestures-to-your-wordpress-site/). However, I would like to reverse the swipeleft and swiperight actions. I have tried without success.
Thanks.

**Comment by GianlucaGuarini** [comment]
Please contact the wordpress plugin author I am not responsible of third party tocca.js implementations
