### ISSUE TITLE
'swipe' event not working without 'preventDefault()' on 'touchmove' event

### ISSUE THREAD

**Issue by Swizz** [GianlucaGuarini/Tocca.js#48]
Hi there !

I use tocca since a while, but recently I encounter a really weird case.

Since days (suspect chrome updates), 'swipe' event does not work anymore without 
```js
elm.addEventListener('touchmove', e => e.preventDefault());
```
_(on the same element)_

So, am I the only one who encounter this issue ?  
May I use a trick to do not copy this thing each time I use a 'swip' event ?
Is a `Tocca` fix possible ?

Cheers,

**Comment by GianlucaGuarini** [comment]
@Swizz could you make an example i could test?

**Comment by Swizz** [comment]
Very sorry about the delay.
I will do it within days.

**Comment by Swizz** [comment]
Without snabbdom everything works like a charm.
It seem to be specific to the event module of snabbdom
I will work on a fix there.

Sorry for stealing your time
