### ISSUE TITLE
event.preventDefault() not working with jQuery

### ISSUE THREAD

**Issue by kimasendorf** [GianlucaGuarini/Tocca.js#49]
I am using Backbone router which makes it neccesary to preventDefault on hyperlinks. When I change 'tap' to 'click' it works like expected.

```
$(document).on('tap', 'a.bb', function(event) {
	event.preventDefault();

	console.log('CLICK');
	var href = $(this).attr('href');
	Backbone.history.navigate(href, true);
});
```

**Comment by GianlucaGuarini** [comment]
You can use `e.originalEvent.preventDefault()` I guess

**Comment by kimasendorf** [comment]
Nope, I tried that..

**Comment by GianlucaGuarini** [comment]
i am closing this issue because there is no default behavior for tocca events so prevent default doesn't make really sense
