### ISSUE TITLE
No events triggered during mobile debug of desktop Chrome 

### ISSUE THREAD

**Issue by ilblog** [GianlucaGuarini/Tocca.js#51]
In the latest version of Chrome tocca works perfect. But when trying to debug app in "simulated" mobile mode, tocca will not emit any events.

After some investigation it turned out that, during initialization of tocca Chrome contains `window.PointerEvent` object but during testing with a mouse (simulating touch gestures) the browser will not emit any pointer events.

**Comment by GianlucaGuarini** [comment]
I am sorry i can not reproduce the issue. Could you please create a test case?

**Comment by sminds** [comment]
In chrome developer tools mobile view.

**Comment by GianlucaGuarini** [comment]
Recently I am experiencing the same issue, I will investigate

**Comment by imlinus** [comment]
I have the same issue. It doesn't work in Inspector Tools simulated device viewer. But it does work in Chrome on Android (HTC 10).

Weird bug. Well. It's nothing we can't live without.. ;)

**Comment by GianlucaGuarini** [comment]
still buggy i will reopen it
