### ISSUE TITLE
swipe won't work crome 62.0.3202 android 5.1.1 SM-J320F build/LMY47V

### ISSUE THREAD

**Issue by englishextra** [GianlucaGuarini/Tocca.js#54]
But it works - Tocca.js 2.0.1 - on same android with firefox 57.0

[But demo here detects events with Chrome 62.0.3202 fine](http://gianlucaguarini.com/Tocca.js/demo-fun.html)

So yes some pages on my sites have:

```css
html,
body {
	height: 100%;
}
body {
	width: 100%;
	overflow-x: hidden;
```
or 
```css
html,
body {
	height: 100%;
}
body {
	width: 100%;
	overflow-y: auto;
```
That's all that I had dug out.

testing page here https://englishextra.github.io/ - swipeup or swipedown

**Important : the events are set to passive.**

```js
var mousewheeldown = document[getElementsByClassName]("mousewheeldown")[0] || "";
var swipeup = document[getElementsByClassName]("swipeup")[0] || "";
if (mousewheeldown && swipeup) {
	if (hasTouch) {
		mousewheeldown[style].display = "none";
		if (root.tocca) {
			root[_addEventListener]("swipeup", revealStart, {passive: true});
			root[_addEventListener]("swipedown", concealStart, {passive: true});
		}
	} else {
		if (hasWheel) {
			swipeup[style].display = "none";
			if (root.WheelIndicator) {
				var indicator;
				indicator = new WheelIndicator({
						elem: root,
						callback: function (e) {
							if ("down" === e.direction) {
								revealStart();
							}
							if ("up" === e.direction) {
								concealStart();
							}
						},
						preventMouse: false
					});
			}
		}
	}
	if (hasTouch || hasWheel) {
		guesture[classList].add(bounceInUpClass);
		guesture[style].display = "block";
	}
}
```
[caniuse says android chrome 62 and webview 62 support passive listeners](https://caniuse.com/#feat=passive-event-listener)

Tocca.js 2.0.1 swipeup and swipedown works in chrome 49.2623.91 on android 6.0.1; P024  build/MMB29M

Doesnt work on my site with Opera 43.02246

**Comment by GianlucaGuarini** [comment]
fixed in v2.0.2

**Comment by englishextra** [comment]
why would you close the issue. can you give me a day or two to test that fix?

**Comment by GianlucaGuarini** [comment]
sorry i guess i will need to reopen it. I am still unhappy with the current result.

**Comment by englishextra** [comment]
@GianlucaGuarini First thing in the morning I can test that. Sorry but your lib is an imortant part in the logic of my apps -  so  any  changes are sensitive.

**Comment by GianlucaGuarini** [comment]
ok now it should be fine. Please check your issue and close it if it was fixed

**Comment by englishextra** [comment]
It works fine, very nice and thanks.
