### ISSUE TITLE
Option "justTouchEvents" doesn't work

### ISSUE THREAD

**Issue by zipper** [GianlucaGuarini/Tocca.js#58]
Regardless of setting "justTouchEvents" to `true` or `false`, `tap` (and other) event is emitted. The reason are these lines of code https://github.com/GianlucaGuarini/Tocca.js/blob/master/Tocca.js#L55-L59. In browser with support for pointer events, event names are set as `Pointer*` and they are listened to on lines https://github.com/GianlucaGuarini/Tocca.js/blob/master/Tocca.js#L246-L248. Therefore simple code as this results in two logs in console:
```javascript
$(document).on('tap click', function(e) {
    console.log(e);
});
```

**Comment by GianlucaGuarini** [comment]
Please provide a demo showing the issue. I am closing this issue because I don't have enough info to debug it
