### ISSUE TITLE
import tocca from 'tocca';

### ISSUE THREAD

**Issue by darrenjacoby** [GianlucaGuarini/Tocca.js#61]
I'm not using jQuery, and while it compiles successfully, I get an error on the frontend; 

`Uncaught ReferenceError: jQuery is not defined`

Tried to search for similar issues but couldn't find any. I have `useJquery` set to false in the options.

**Comment by GianlucaGuarini** [comment]
could you please reproduce the issue in a small demo?

**Comment by darrenjacoby** [comment]
@GianlucaGuarini I'll see what I can do, should be said that I'm using ES6 and babel/webpack.

**Comment by GianlucaGuarini** [comment]
I use `Tocca.js` and webpack in many production projects without any issue I am sure the problem is somewhere else. Please try to reproduce the problem and I will be happy to reopen this issue.
