### ISSUE TITLE
Issue with longtap and native pinch and zoom

### ISSUE THREAD

**Issue by Darkle** [GianlucaGuarini/Tocca.js#62]
Hi, I think I've found a bug in tocca. It seems that a 'longtap' event is triggered when you use the native pinch and zoom to zoom in to an image on the page. Increasing the `longtapThreshold` doesnt seem to help.

**Comment by GianlucaGuarini** [comment]
thanks for reporting it. It should be trivial to fix it. I will look into it asap

**Comment by GianlucaGuarini** [comment]
fixed in v2.0.4 thank you
