### ISSUE TITLE
inline Events working?

### ISSUE THREAD

**Issue by number005** [GianlucaGuarini/Tocca.js#64]
I just played around with the demo, and its working perfectly.

Not when I change the code to Inline Events it's not working anymore.

`<div onlongtap="function(e){
	alert('World');
})" id="test"></div>`

I "long tap" and nothing happens! WhenI use "addEventListener", it is working again. Could you help me?

**Comment by GianlucaGuarini** [comment]
I have update the documentation. Inline events are supported only together with Riot.js https://plnkr.co/edit/rfNYHDp6tzU1w3h5TVef?p=preview
