### ISSUE TITLE
TypeError on Mobile Safari UI/WKWebView 13.1.X

### ISSUE THREAD

**Issue by andreacimino** [GianlucaGuarini/Tocca.js#65]
The iOS users of my Cordova app started exhibiting the problem after they upgraded their system to latest iOS version. Now tocca exhibits this problem:

TypeError: undefined is not an object

This is shown here in the latest version of tocca in this particular code:

   var pointer = getPointerEvent(e)
   currX = pointer.pageX  <- Here pointer is undefined

This issue is shown randomly I was not able to reproduce with my iPhone SE, I will try to understand which devices affect the problem with more debugging.

I am using Tocca with this configuration.
 window.tocca({
          useJquery: false
        });

**Comment by Aarbel** [comment]
Do you still face this problem ?

iOS13 WkWebview handles touch and click events in a different way. They broke a lot of stacks...
