### ISSUE TITLE
Start from v2.0.5, tap/swipe events cannot be triggered on Android Chrome 79.0

### ISSUE THREAD

**Issue by hit1205** [GianlucaGuarini/Tocca.js#69]
I found that the the `tap`, `swipeup`, `swipedown`, `swipeleft`, `swiperight` event cannot be triggered on the [offical demo](https://gianlucaguarini.com/Tocca.js/demo-fun.html) when I use Chrome on Android, only `dbtap` and `longtap` event can be triggered.

I tried on the same page structure and replace the version of `Tocca.js`, found that the `tap` event cannot be trigged on v2.0.5, v2.0.6, but can be trigger on v2.0.3, v2.0.4

Chrome Version: 79.0.3945.93
Android Version: 9 (Sony Xperia XZ1, update 47.2.A.11.228)

**Comment by GianlucaGuarini** [comment]
I can reproduce the issue thank you for reporting it

**Comment by GianlucaGuarini** [comment]
Fixed in tocca@2.0.7
