### ISSUE TITLE
TypeError undefined is not an object (evaluating 't.targetTouches[0].pageX')

### ISSUE THREAD

**Issue by CPatchane** [GianlucaGuarini/Tocca.js#70]
Seems to be specific to iOS > v13
<img width="895" alt="Screenshot 2020-01-06 at 15 17 50" src="https://user-images.githubusercontent.com/10224453/71823832-7b4c9480-3098-11ea-8ca4-6bbec0e7c985.png">

**Comment by GianlucaGuarini** [comment]
fixed in 2.0.9 thank you for reporting it
